-- CREATE THE SHOP DATABASE
CREATE SCHEMA `shop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CREATE THE USER TABLE
CREATE TABLE IF NOT EXISTS `shop`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `middleName` VARCHAR(50) NULL DEFAULT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL,
  `mobile` VARCHAR(15) NULL,
  `passwordHash` VARCHAR(32) NOT NULL,
  `admin` TINYINT NOT NULL DEFAULT 0,
  `registeredAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unq_mobile` (`mobile` ASC),
  UNIQUE INDEX `unq_email` (`email` ASC) );

  -- CREATE THE CATEGORIES TABLE
  CREATE TABLE IF NOT EXISTS `shop`.`categories` (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  categoryName VARCHAR(255) NOT NULL
);
ALTER TABLE `shop`.`categories` 
ADD  UNIQUE INDEX `idx_category` (`categoryName` ASC);